# Generated by Django 6.0.1 on 2026-01-19 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsersList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "User List",
                "verbose_name_plural": "Users List",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("birth", models.CharField(max_length=255, null=True)),
                ("age", models.IntegerField(null=True)),
                ("image", models.FileField(null=True, upload_to="public")),
                (
                    "UsersList",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.userslist"
                    ),
                ),
            ],
        ),
    ]
