# Generated by Django 6.0.1 on 2026-01-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userslist",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
