# Generated by Django 6.0.1 on 2026-01-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_seasons_episodes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Episodes",
            new_name="Episode",
        ),
        migrations.RenameModel(
            old_name="Seasons",
            new_name="Season",
        ),
    ]
