# Generated by Django 6.0.1 on 2026-01-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_episodes_episode_rename_seasons_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
