# Generated by Django 6.0.1 on 2026-01-28 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_episode_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActorsList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Actor List",
                "verbose_name_plural": "Actors List",
            },
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_name", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("image", models.FileField(null=True, upload_to="public")),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.season"
                    ),
                ),
                (
                    "UsersList",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.actorslist"
                    ),
                ),
            ],
        ),
    ]
