# Generated by Django 6.0.1 on 2026-01-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_actorslist_actor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actor",
            old_name="UsersList",
            new_name="ActorsList",
        ),
    ]
